extends:
  - airbnb-base
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:import/typescript'
root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
env:
  node: true
ignorePatterns:
  - build/**/*
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  no-console:
    - off
  '@typescript-eslint/no-var-requires':
    - off
  'import/prefer-default-export':
    - off
  'import/extensions':
    - error
    - ignorePackages
  'import/order':
    - error
    - newlines-between: always
      alphabetize:
        order: asc
  'import/no-unresolved':
    - off
  'arrow-parens':
    - off
  'implicit-arrow-linebreak':
    - off
  'operator-linebreak':
    - off
