extends:
  - airbnb-base
  - "plugin:@typescript-eslint/recommended"
root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
env:
  node: true
rules:
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  no-console:
    - off
  "@typescript-eslint/no-var-requires":
    - off
