language: node_js
node_js:
- '7'
script: npm run ci
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: buriedunderbooks@hotmail.com
  on:
    tags: true
  api_key:
    secure: OhZlN6+tVMfao3WoBDDM8hdFielxhXd7fWNJc2a7btGBQdFvXjoahELfmXLx2KAFpibcLEmQd7XKkfm+l1wXvAevF9fb1PKYm/z3SW7O2K8de4JQfRFknQrBpshiWssqE+I0mBtmZ80YsH1XZhVbPDr/7CUp2g9QJmPlNb8tPvAEcANt0wa0/kkF9l4+8w1KC067ooL+cotjcXSPXuK9+obhzxvpwGoXqvEXT8R6hr2TBQFBPqTrx1UqU12lSiLgpT+Q38F28zvhgIZ5uV/wvUXiwRzpGijvU7uNGXmzfEc3NKfvHkKG3PKDEjwGNvmsTPv9C6OIRSUx1IVhSdZieWCSx1kMGXkBgF4O6ZS5TDMzisVryIoXcGUoO3JphRLsBzMaw0moZpFdn3TA9DqftZSdgrvDhwtPGUAjow+CNWGOc13HZY6HAAI4/LqgS/TNopPXB1BzwkvB6PGCOyWNJRVhQttB0bJekagrVHs44KzzAfGK099RzVqkU+DFwIgEsP6RicQVOiQH/OObXygFPCGm70wO2tAuhpKe++3twU+9qACzOYs6aKSqrzVdl504Q/9p7nfCgcjjwe+NFzphYxfaM2neghf28S+yycmEvvRb5J45G++Xpek8hVYCxMTmmN/HjmhxixS2zxmYhfu14OWZKuaISIpfCw74XRZ4H2Q=
