language: node_js
node_js:
- '7'
script: npm run spellchecker && npm run lint && npm test
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: buriedunderbooks@hotmail.com
  on:
    tags: true
  api_key:
    secure: z6uV5fQPRB4KYU4W/86Lbuwra8NZQ4zxLWnNfGtx+yKU2A24AJY9jO+0M+VkpXgGV0cjOEHU5hloEP+GT6GJyNEgHt/OQUxlorGqVj+fcvAWJmq4xGrEHh9kr61b/OaJtNVtvUzBQifymORtjrB+v6BfV5sg/LICvj/ROIyR1Gnx/5HO/sxeKiqldgb4dr+ib1yN07bafOYyHz5k13+eb1i5oZauv4Ehx6XwYsPACroHQ3QTtS+f5kePUa+nf3wsm9W6q5EDu8jc77kAokItoKcRRSGqOG26plqr9A+HndTrXY11BjkojpG64oPQpEs5ACXKwBVB6SCGSaztXU3ERo5vG9h6pwb6lf8qZYPoYh0CQ84ej5SXKUHsjMu93qLc4aD88MbyImoK0aeVfgzOCt+Lal8bzYvAWMChHh3kIgIUFn2FKvZr5F5lLtB1cjjNjbqa0up/04hOLRIq/tTrRUElGoAJHSR88UTYSrLvRnNAXnKVE3HZ106SwaBKzVwBQ88kAtMQLA1uykRmRVWm4mDWXJpn+JfCbAJpbgP8DVdi3C88Pu3I5lR2xVLyfnmGk/sssyMRfbtoxhbvfgp4WoH3skPtUucYmDSraCT1lPjU6T5wasKwkrny9vc7VyJaFq2ktgFLuEDn+Kzepzo848lBOZ6h+8X9NA66y3mziP0=
